import type { ConstellationInfo } from '@/types'

export const constellations: ConstellationInfo[] = [
  {
    id: 'starlink',
    name: 'Starlink',
    type: 'leo',
    satelliteIds: ['SAT-SL-1', 'SAT-SL-2', 'SAT-SL-3', 'SAT-SL-4', 'SAT-SL-5'],
    color: '#22d3ee',
    coverageRadius: 2500,
    healthStatus: 'healthy',
    operator: 'SpaceX',
  },
  {
    id: 'gps',
    name: 'GPS',
    type: 'meo',
    satelliteIds: ['SAT-GPS-1', 'SAT-GPS-2', 'SAT-GPS-3', 'SV-003'],
    color: '#22c55e',
    coverageRadius: 8000,
    healthStatus: 'healthy',
    operator: 'USSF',
  },
  {
    id: 'galileo',
    name: 'Galileo',
    type: 'meo',
    satelliteIds: ['SAT-GAL-1', 'SAT-GAL-2', 'SAT-GAL-3'],
    color: '#3b82f6',
    coverageRadius: 7500,
    healthStatus: 'healthy',
    operator: 'ESA',
  },
  {
    id: 'glonass',
    name: 'GLONASS',
    type: 'meo',
    satelliteIds: ['SAT-GLO-1', 'SAT-GLO-2', 'SAT-GLO-3'],
    color: '#ef4444',
    coverageRadius: 7800,
    healthStatus: 'degraded',
    operator: 'Roscosmos',
  },
  {
    id: 'osprey-sim',
    name: 'OSPREY Simulation',
    type: 'leo',
    satelliteIds: ['SV-001', 'SV-002', 'SV-004'],
    color: '#f59e0b',
    coverageRadius: 3000,
    healthStatus: 'healthy',
    operator: 'OSPREY Systems',
  },
]
