import type { FeedEvent } from '@/types'

export const feed: FeedEvent[] = [
  {
    id: 'FE-001',
    type: 'intel',
    severity: 'critical',
    title: 'Aircraft Detected',
    body: 'Unidentified aircraft entering ADIZ at bearing 045, range 120 nm. Transponder offline. Intercept scrambled.',
    timestamp: '2026-06-15T08:20:00Z',
    source: 'EWS-ALPHA',
    assetIds: ['AC-003', 'AC-009'],
    threatLevel: 'critical',
  },
  {
    id: 'FE-002',
    type: 'movement',
    severity: 'high',
    title: 'Signal Acquired',
    body: 'HF signal triangulated to grid 47Q ME 8123 4567. Classified as emission type X-band fire control radar.',
    timestamp: '2026-06-15T08:18:30Z',
    source: 'SIGINT-FWD',
    assetIds: ['SV-001', 'SV-004'],
    threatLevel: 'high',
  },
  {
    id: 'FE-003',
    type: 'status',
    severity: 'medium',
    title: 'Route Updated',
    body: 'USS Abraham Lincoln routing adjusted northbound. ETA Strait of Hormuz revised to 14:30 ZULU.',
    timestamp: '2026-06-15T08:15:00Z',
    source: 'MOC-CENTCOM',
    assetIds: ['MV-001'],
    threatLevel: 'medium',
  },
  {
    id: 'FE-004',
    type: 'intel',
    severity: 'low',
    title: 'Orbital Pass',
    body: 'KH-11 recon pass over grid 38S. Collection window open for next 12 minutes. Downlink scheduled at T+8.',
    timestamp: '2026-06-15T08:12:00Z',
    source: 'NRO-DSO',
    assetIds: ['SV-001'],
    threatLevel: 'low',
  },
  {
    id: 'FE-005',
    type: 'report',
    severity: 'high',
    title: 'Convoy Spotted',
    body: 'Satellite imagery confirms 6-vessel convoy departing Bushehr. Two warships escorting. Course 145 true.',
    timestamp: '2026-06-15T08:10:00Z',
    source: 'NGA-BAHRAIN',
    assetIds: ['SV-002', 'MV-001'],
    threatLevel: 'high',
  },
  {
    id: 'FE-006',
    type: 'movement',
    severity: 'medium',
    title: 'Course Change Detected',
    body: 'PLANS Lhasa altered course to 170 degrees at 20 kts. Projected track intersects SLOC Charlie.',
    timestamp: '2026-06-15T08:08:00Z',
    source: 'FMP-SHARE',
    assetIds: ['MV-009'],
    threatLevel: 'medium',
  },
  {
    id: 'FE-007',
    type: 'intel',
    severity: 'critical',
    title: 'Cyber Intrusion Attempt',
    body: 'Unauthorized access attempt detected on TACNET node 7. Source IP traced to satellite relay. Countermeasures active.',
    timestamp: '2026-06-15T08:05:00Z',
    source: 'CYBERCOM-FWD',
    assetIds: ['SV-003', 'SV-005'],
    threatLevel: 'critical',
  },
  {
    id: 'FE-008',
    type: 'status',
    severity: 'low',
    title: 'Fuel State Advisory',
    body: 'SENTRY-1 reports bingo fuel at current loiter. Tanker KH-135 on station at WP-7 for scheduled rendezvous.',
    timestamp: '2026-06-15T08:03:00Z',
    source: 'AMC-ALPHA',
    assetIds: ['AC-001', 'AC-008'],
    threatLevel: 'low',
  },
  {
    id: 'FE-009',
    type: 'report',
    severity: 'high',
    title: 'Pirate Activity Warning',
    body: 'Small craft activity detected 40 nm east of Socotra. Three skiffs, possible mothership. Transiting vessels advised.',
    timestamp: '2026-06-15T07:58:00Z',
    source: 'UKMTO',
    assetIds: ['MV-004', 'MV-010'],
    threatLevel: 'high',
  },
  {
    id: 'FE-010',
    type: 'intel',
    severity: 'medium',
    title: 'Radar Emission Detected',
    body: 'JORN radar system detected emissions from -12.789, 96.234. Coincides with P-8A Poseidon patrol track.',
    timestamp: '2026-06-15T07:55:00Z',
    source: 'ELINT-7',
    assetIds: ['AC-005'],
    threatLevel: 'medium',
  },
  {
    id: 'FE-011',
    type: 'movement',
    severity: 'low',
    title: 'SAR Satellite Re-tasked',
    body: 'SAR-Lupe 5 re-tasked to grid 49Q for emergency flood assessment. Tasking priority override authorized.',
    timestamp: '2026-06-15T07:50:00Z',
    source: 'GEOSOL-SOUTH',
    assetIds: ['SV-002'],
    threatLevel: 'low',
  },
  {
    id: 'FE-012',
    type: 'intel',
    severity: 'critical',
    title: 'Ballistic Missile Signatures',
    body: 'Infrared signature detected from launch site 34.234, 44.567. Boost phase. Impact assessment underway.',
    timestamp: '2026-06-15T07:45:00Z',
    source: 'SBIRS-1',
    assetIds: ['SV-003', 'SV-005'],
    threatLevel: 'critical',
  },
  {
    id: 'FE-013',
    type: 'status',
    severity: 'medium',
    title: 'Communications Relay Degraded',
    body: 'AEHF-6 experiencing intermittent power fluctuation on channel 4. Backup routing via DSCS activated.',
    timestamp: '2026-06-15T07:42:00Z',
    source: 'SSC-SPACE',
    assetIds: ['SV-003'],
    threatLevel: 'medium',
  },
  {
    id: 'FE-014',
    type: 'movement',
    severity: 'high',
    title: 'Submarine Contact Possible',
    body: 'Magnetic anomaly detected along shipping lane 9. P-8A deploying sonobuoys. MAD contact pending.',
    timestamp: '2026-06-15T07:38:00Z',
    source: 'ASW-4',
    assetIds: ['AC-005'],
    threatLevel: 'high',
  },
  {
    id: 'FE-015',
    type: 'report',
    severity: 'low',
    title: 'Maintenance Complete',
    body: 'CH-53K King Stallion phase maintenance complete. Rotor torque recalibrated. Returned to standby.',
    timestamp: '2026-06-15T07:30:00Z',
    source: 'MCO-JAPAN',
    assetIds: ['AC-010'],
    threatLevel: 'none',
  },
  {
    id: 'FE-016',
    type: 'intel',
    severity: 'medium',
    title: 'Electronic Warfare Exercise',
    body: 'EW jamming signals detected originating from grid 31S. Duration 4 min. Spectrum analysis shows DRFM techniques.',
    timestamp: '2026-06-15T07:25:00Z',
    source: 'EWS-DELTA',
    assetIds: ['SV-001', 'SV-004'],
    threatLevel: 'medium',
  },
  {
    id: 'FE-017',
    type: 'movement',
    severity: 'high',
    title: 'Unknown Vessel Approaching',
    body: 'Civilian radar contact at 31.567, 32.345. Vessel identified as Ever Given proceeding north through canal. Standard transit.',
    timestamp: '2026-06-15T07:20:00Z',
    source: 'SCA-ADMIN',
    assetIds: ['MV-010'],
    threatLevel: 'low',
  },
  {
    id: 'FE-018',
    type: 'report',
    severity: 'medium',
    title: 'Weather Degradation',
    body: 'Tropical disturbance forming 200 nm east of Guam. Projected to strengthen. Affecting recon ops in quadrant 7.',
    timestamp: '2026-06-15T07:15:00Z',
    source: 'NAVPACMETOC',
    assetIds: ['AC-002'],
    threatLevel: 'medium',
  },
  {
    id: 'FE-019',
    type: 'intel',
    severity: 'high',
    title: 'Transponder Anomaly',
    body: 'SENTRY-1 IFF mode-4 intermittent. Secondary radar contact degraded. Maintain EMCON delta until diagnostics complete.',
    timestamp: '2026-06-15T07:10:00Z',
    source: 'CRC-TABOR',
    assetIds: ['AC-001'],
    threatLevel: 'high',
  },
  {
    id: 'FE-020',
    type: 'movement',
    severity: 'medium',
    title: 'Task Group Formation',
    body: 'JS Izumo, FS Charles de Gaulle forming joint task group at grid 47R. Coordinated ASW exercise expected.',
    timestamp: '2026-06-15T07:05:00Z',
    source: 'JMSDF-2',
    assetIds: ['MV-002', 'MV-006'],
    threatLevel: 'medium',
  },
]
