import type { Geofence } from '@/types'

export const geofences: Geofence[] = [
  {
    id: 'gf-pentagon',
    name: 'Pentagon',
    category: 'military-base',
    shape: 'circle',
    priority: 'critical',
    status: 'active',
    description: 'Primary military command center - restricted airspace',
    latitude: 38.8719,
    longitude: -77.0563,
    radiusKm: 300,
  },
  {
    id: 'gf-norfolk',
    name: 'Norfolk Naval Station',
    category: 'naval-facility',
    shape: 'circle',
    priority: 'high',
    status: 'active',
    description: 'World\'s largest naval base - restricted maritime zone',
    latitude: 36.9468,
    longitude: -76.3170,
    radiusKm: 200,
  },
  {
    id: 'gf-diego-garcia',
    name: 'Diego Garcia',
    category: 'military-base',
    shape: 'circle',
    priority: 'high',
    status: 'active',
    description: 'Strategic Indian Ocean base - restricted zone',
    latitude: -7.3133,
    longitude: 72.4111,
    radiusKm: 250,
  },
  {
    id: 'gf-dprk-border',
    name: 'DMZ Surveillance Zone',
    category: 'surveillance-area',
    shape: 'circle',
    priority: 'critical',
    status: 'warning',
    description: 'Korean Demilitarized Zone - heightened surveillance',
    latitude: 37.9550,
    longitude: 126.9900,
    radiusKm: 150,
  },
  {
    id: 'gf-guantanamo',
    name: 'Guantanamo Bay',
    category: 'naval-facility',
    shape: 'circle',
    priority: 'high',
    status: 'active',
    description: 'US Naval Base Cuba - restricted maritime zone',
    latitude: 19.9060,
    longitude: -75.1470,
    radiusKm: 180,
  },
  {
    id: 'gf-ramstein',
    name: 'Ramstein Air Base',
    category: 'airbase',
    shape: 'circle',
    priority: 'high',
    status: 'active',
    description: 'Major US Air Force base in Europe',
    latitude: 49.4368,
    longitude: 7.6003,
    radiusKm: 200,
  },
  {
    id: 'gf-yokota',
    name: 'Yokota Air Base',
    category: 'airbase',
    shape: 'circle',
    priority: 'medium',
    status: 'active',
    description: 'US Forces Japan headquarters',
    latitude: 35.7485,
    longitude: 139.3481,
    radiusKm: 150,
  },
  {
    id: 'gf-bahrain',
    name: 'NSA Bahrain',
    category: 'naval-facility',
    shape: 'circle',
    priority: 'high',
    status: 'active',
    description: 'US Naval Support Activity - 5th Fleet HQ',
    latitude: 26.2167,
    longitude: 50.5833,
    radiusKm: 120,
  },
  {
    id: 'gf-incirlik',
    name: 'Incirlik Air Base',
    category: 'airbase',
    shape: 'circle',
    priority: 'medium',
    status: 'active',
    description: 'Strategic NATO air base in southern Turkey',
    latitude: 37.0006,
    longitude: 35.4259,
    radiusKm: 150,
  },
  {
    id: 'gf-sigonella',
    name: 'NAS Sigonella',
    category: 'naval-facility',
    shape: 'circle',
    priority: 'medium',
    status: 'active',
    description: 'Naval Air Station in Sicily - Mediterranean hub',
    latitude: 37.4017,
    longitude: 14.9222,
    radiusKm: 120,
  },
]
