import type { GroundStation, DataSourceInfo } from '@/types'

const GS_SOURCE: DataSourceInfo = {
  source: 'OSPREY Simulation Engine',
  lastUpdated: new Date().toISOString(),
  refreshRate: 'static (simulated)',
  confidence: 0.7,
  dataQuality: 'simulated',
}

export const groundStations = [
  {
    id: 'GS-001',
    name: 'Northrop Grumman - Aurora',
    type: 'ground-station',
    latitude: 39.7294,
    longitude: -104.8319,
    altitude: 1640,
    status: 'active',
    lastUpdated: '2026-06-15T08:00:00Z',
    dataSource: GS_SOURCE,
    coverageRadiusKm: 2500,
    connectedSatelliteIds: ['SV-001', 'SV-003'],
    country: 'USA',
    operator: 'Northrop Grumman',
  },
  {
    id: 'GS-002',
    name: 'Svalbard Satellite Station',
    latitude: 78.2297,
    longitude: 15.4077,
    altitude: 400,
    type: 'ground-station',
    status: 'active',
    lastUpdated: '2026-06-15T08:00:00Z',
    dataSource: GS_SOURCE,
    coverageRadiusKm: 3000,
    connectedSatelliteIds: ['SV-002'],
    country: 'Norway',
    operator: 'KSAT',
  },
  {
    id: 'GS-003',
    name: 'Diego Garcia Station',
    latitude: -7.3126,
    longitude: 72.4111,
    altitude: 10,
    type: 'ground-station',
    status: 'active',
    lastUpdated: '2026-06-15T08:00:00Z',
    dataSource: GS_SOURCE,
    coverageRadiusKm: 2000,
    connectedSatelliteIds: ['SV-004', 'SV-005'],
    country: 'UK (BIOT)',
    operator: 'US Space Force',
  },
] as GroundStation[]
