import type { OntologyClass, RelationDef, Axiom } from '@/types'

export const ontologyClasses: OntologyClass[] = [
  {
    id: 'Thing',
    name: 'Thing',
    description: 'Root concept — every entity is a Thing',
    parentIds: [],
    properties: [],
    color: '#6b7280',
    icon: 'circle',
    displayOrder: 0,
  },
  {
    id: 'Asset',
    name: 'Asset',
    description: 'Any trackable operational asset',
    parentIds: ['Thing'],
    properties: [
      { name: 'status', type: 'enum', description: 'Current operational status', required: true, enumValues: ['active', 'standby', 'offline', 'maintenance', 'unknown', 'lost'] },
      { name: 'latitude', type: 'number', description: 'Degrees north', required: true, range: [-90, 90], unit: '°' },
      { name: 'longitude', type: 'number', description: 'Degrees east', required: true, range: [-180, 180], unit: '°' },
      { name: 'altitude', type: 'number', description: 'Meters AMSL', required: true, unit: 'm' },
      { name: 'speed', type: 'number', description: 'Knots', required: true, unit: 'kn' },
      { name: 'heading', type: 'number', description: 'Degrees true north', required: true, range: [0, 360], unit: '°' },
    ],
    color: '#94a3b8',
    icon: 'hexagon',
    displayOrder: 1,
  },
  {
    id: 'Aircraft',
    name: 'Aircraft',
    description: 'Airborne fixed-wing or rotary-wing platform',
    parentIds: ['Asset'],
    properties: [
      { name: 'callsign', type: 'string', description: 'Radio call sign', required: false },
      { name: 'icao', type: 'string', description: 'ICAO 24-bit address', required: false },
      { name: 'range', type: 'number', description: 'Maximum operational range', required: true, unit: 'km' },
      { name: 'fuelLevel', type: 'number', description: 'Fraction of fuel remaining', required: true, range: [0, 1] },
    ],
    color: '#22d3ee',
    icon: 'plane',
    displayOrder: 2,
  },
  {
    id: 'FixedWing',
    name: 'Fixed-Wing',
    description: 'Conventional aircraft with fixed wings',
    parentIds: ['Aircraft'],
    properties: [],
    color: '#22d3ee',
    icon: 'plane',
    displayOrder: 3,
  },
  {
    id: 'RotaryWing',
    name: 'Rotary-Wing',
    description: 'Helicopter or VTOL platform',
    parentIds: ['Aircraft'],
    properties: [
      { name: 'rotorCount', type: 'number', description: 'Number of rotors', required: false, range: [1, 8] },
    ],
    color: '#67e8f9',
    icon: 'plane',
    displayOrder: 4,
  },
  {
    id: 'Maritime',
    name: 'Maritime',
    description: 'Surface vessel or underwater platform',
    parentIds: ['Asset'],
    properties: [
      { name: 'mmsi', type: 'string', description: 'MMSI identifier', required: true },
      { name: 'imo', type: 'string', description: 'IMO number', required: false },
      { name: 'destination', type: 'string', description: 'Current intended destination', required: false },
      { name: 'draft', type: 'number', description: 'Vertical distance waterline to keel', required: true, unit: 'm' },
      { name: 'length', type: 'number', description: 'Overall length', required: true, unit: 'm' },
      { name: 'beam', type: 'number', description: 'Maximum beam', required: true, unit: 'm' },
    ],
    color: '#4ade80',
    icon: 'ship',
    displayOrder: 2,
  },
  {
    id: 'Satellite',
    name: 'Satellite',
    description: 'Orbital space asset',
    parentIds: ['Asset'],
    properties: [
      { name: 'noradId', type: 'string', description: 'NORAD catalogue number', required: true },
      { name: 'inclination', type: 'number', description: 'Orbital inclination', required: true, range: [0, 180], unit: '°' },
      { name: 'apogee', type: 'number', description: 'Highest altitude in orbit', required: true, unit: 'km' },
      { name: 'perigee', type: 'number', description: 'Lowest altitude in orbit', required: true, unit: 'km' },
      { name: 'period', type: 'number', description: 'Orbital period', required: true, unit: 'min' },
    ],
    color: '#fbbf24',
    icon: 'satellite',
    displayOrder: 2,
  },
  {
    id: 'LEOSatellite',
    name: 'LEO Satellite',
    description: 'Low Earth Orbit satellite (< 2000 km)',
    parentIds: ['Satellite'],
    properties: [],
    color: '#fcd34d',
    icon: 'satellite',
    displayOrder: 5,
  },
  {
    id: 'GEOSatellite',
    name: 'GEO Satellite',
    description: 'Geostationary Earth Orbit satellite (~35,786 km)',
    parentIds: ['Satellite'],
    properties: [],
    color: '#f59e0b',
    icon: 'satellite',
    displayOrder: 5,
  },
  {
    id: 'GroundStation',
    name: 'Ground Station',
    description: 'Fixed ground-based communications or TT&C facility',
    parentIds: ['Thing'],
    properties: [
      { name: 'coverageRadiusKm', type: 'number', description: 'Line-of-sight coverage radius', required: true, unit: 'km' },
      { name: 'country', type: 'string', description: 'Host nation', required: true },
      { name: 'operator', type: 'string', description: 'Operating organisation', required: true },
      { name: 'status', type: 'enum', description: 'Operational status', required: true, enumValues: ['active', 'standby', 'maintenance', 'offline'] },
    ],
    color: '#818cf8',
    icon: 'radio',
    displayOrder: 6,
  },
  {
    id: 'Mission',
    name: 'Mission',
    description: 'A structured operation with defined objectives and assigned assets',
    parentIds: ['Thing'],
    properties: [
      { name: 'status', type: 'enum', description: 'Current mission phase', required: true, enumValues: ['pending', 'in-progress', 'completed', 'aborted', 'standby', 'cancelled'] },
      { name: 'objective', type: 'string', description: 'Primary mission objective', required: true },
      { name: 'region', type: 'string', description: 'Geographic scope', required: true },
      { name: 'threatLevel', type: 'enum', description: 'Assessed threat level', required: true, enumValues: ['none', 'low', 'medium', 'high', 'critical'] },
    ],
    color: '#a78bfa',
    icon: 'target',
    displayOrder: 7,
  },
  {
    id: 'IntelMission',
    name: 'Intelligence Mission',
    description: 'SIGINT/ELINT/COMINT collection operation',
    parentIds: ['Mission'],
    properties: [],
    color: '#c4b5fd',
    icon: 'target',
    displayOrder: 8,
  },
  {
    id: 'CombatMission',
    name: 'Combat Mission',
    description: 'Offensive or defensive kinetic operation',
    parentIds: ['Mission'],
    properties: [],
    color: '#f87171',
    icon: 'target',
    displayOrder: 8,
  },
  {
    id: 'Region',
    name: 'Region',
    description: 'Geographic area of interest with operational context',
    parentIds: ['Thing'],
    properties: [
      { name: 'bounds', type: 'string', description: 'Bounding box (N,S,E,W)', required: true },
      { name: 'threatLevel', type: 'enum', description: 'Current threat assessment', required: true, enumValues: ['none', 'low', 'medium', 'high', 'critical'] },
    ],
    color: '#60a5fa',
    icon: 'map',
    displayOrder: 9,
  },
  {
    id: 'Alert',
    name: 'Alert',
    description: 'A time-critical notification triggered by events or rule violations',
    parentIds: ['Thing'],
    properties: [
      { name: 'severity', type: 'enum', description: 'Alert severity level', required: true, enumValues: ['low', 'medium', 'high', 'critical'] },
      { name: 'acknowledged', type: 'boolean', description: 'Whether the alert has been acknowledged', required: true },
    ],
    color: '#f87171',
    icon: 'bell',
    displayOrder: 10,
  },
  {
    id: 'Constellation',
    name: 'Constellation',
    description: 'A group of satellites operating as a coordinated system',
    parentIds: ['Thing'],
    properties: [
      { name: 'type', type: 'enum', description: 'Orbital regime', required: true, enumValues: ['leo', 'meo', 'geo', 'heo'] },
      { name: 'healthStatus', type: 'enum', description: 'Overall constellation health', required: true, enumValues: ['healthy', 'degraded', 'critical'] },
      { name: 'operator', type: 'string', description: 'Operating organisation', required: true },
    ],
    color: '#34d399',
    icon: 'globe',
    displayOrder: 11,
  },
  {
    id: 'Geofence',
    name: 'Geofence',
    description: 'A virtual geographic boundary with alerting rules',
    parentIds: ['Thing'],
    properties: [
      { name: 'category', type: 'enum', description: 'Type of restricted area', required: true, enumValues: ['restricted-area', 'military-base', 'airbase', 'naval-facility', 'radar-installation', 'mission-zone', 'surveillance-area'] },
      { name: 'priority', type: 'enum', description: 'Operational priority', required: true, enumValues: ['critical', 'high', 'medium', 'low'] },
      { name: 'status', type: 'enum', description: 'Current fence status', required: true, enumValues: ['active', 'inactive', 'warning', 'breached'] },
    ],
    color: '#fb923c',
    icon: 'shield',
    displayOrder: 12,
  },
]

export const relationDefs: RelationDef[] = [
  {
    id: 'assigned-to',
    name: 'Assigned To',
    description: 'An asset is assigned to a mission',
    domain: ['Asset'],
    range: ['Mission'],
    inverse: 'has-asset',
    isFunctional: false,
    isTransitive: false,
    isSymmetric: false,
  },
  {
    id: 'has-asset',
    name: 'Has Asset',
    description: 'A mission includes an asset',
    domain: ['Mission'],
    range: ['Asset'],
    inverse: 'assigned-to',
    isFunctional: false,
    isTransitive: false,
    isSymmetric: false,
  },
  {
    id: 'located-in',
    name: 'Located In',
    description: 'An entity is geographically within a region',
    domain: ['Asset', 'GroundStation', 'Geofence'],
    range: ['Region'],
    inverse: 'contains',
    isFunctional: false,
    isTransitive: true,
    isSymmetric: false,
  },
  {
    id: 'contains',
    name: 'Contains',
    description: 'A region contains an entity',
    domain: ['Region'],
    range: ['Asset', 'GroundStation', 'Geofence'],
    inverse: 'located-in',
    isFunctional: false,
    isTransitive: true,
    isSymmetric: false,
  },
  {
    id: 'triggers',
    name: 'Triggers',
    description: 'An alert is triggered by an asset or event',
    domain: ['Alert'],
    range: ['Asset'],
    inverse: 'triggers-alert',
    isFunctional: false,
    isTransitive: false,
    isSymmetric: false,
  },
  {
    id: 'triggers-alert',
    name: 'Triggers Alert',
    description: 'An asset triggered an alert',
    domain: ['Asset'],
    range: ['Alert'],
    inverse: 'triggers',
    isFunctional: false,
    isTransitive: false,
    isSymmetric: false,
  },
  {
    id: 'monitors',
    name: 'Monitors',
    description: 'A mission monitors a region',
    domain: ['Mission'],
    range: ['Region'],
    inverse: 'monitored-by',
    isFunctional: false,
    isTransitive: false,
    isSymmetric: false,
  },
  {
    id: 'monitored-by',
    name: 'Monitored By',
    description: 'A region is monitored by a mission',
    domain: ['Region'],
    range: ['Mission'],
    inverse: 'monitors',
    isFunctional: false,
    isTransitive: false,
    isSymmetric: false,
  },
  {
    id: 'communicates-with',
    name: 'Communicates With',
    description: 'Two entities have an active communication link',
    domain: ['Satellite', 'GroundStation'],
    range: ['Satellite', 'GroundStation'],
    isFunctional: false,
    isTransitive: false,
    isSymmetric: true,
  },
  {
    id: 'part-of',
    name: 'Part Of',
    description: 'A satellite belongs to a constellation',
    domain: ['Satellite'],
    range: ['Constellation'],
    inverse: 'has-member',
    isFunctional: false,
    isTransitive: true,
    isSymmetric: false,
  },
  {
    id: 'has-member',
    name: 'Has Member',
    description: 'A constellation includes a satellite',
    domain: ['Constellation'],
    range: ['Satellite'],
    inverse: 'part-of',
    isFunctional: false,
    isTransitive: true,
    isSymmetric: false,
  },
  {
    id: 'crosses',
    name: 'Crosses',
    description: 'An asset crosses a geofence boundary',
    domain: ['Asset'],
    range: ['Geofence'],
    inverse: 'crossed-by',
    isFunctional: false,
    isTransitive: false,
    isSymmetric: false,
  },
  {
    id: 'crossed-by',
    name: 'Crossed By',
    description: 'A geofence is crossed by an asset',
    domain: ['Geofence'],
    range: ['Asset'],
    inverse: 'crosses',
    isFunctional: false,
    isTransitive: false,
    isSymmetric: false,
  },
]

export const axiomDefs: Axiom[] = [
  {
    id: 'disjoint-aircraft-maritime',
    type: 'disjoint',
    description: 'Aircraft and Maritime are disjoint',
    params: { classA: 'Aircraft', classB: 'Maritime' },
  },
  {
    id: 'disjoint-aircraft-satellite',
    type: 'disjoint',
    description: 'Aircraft and Satellite are disjoint',
    params: { classA: 'Aircraft', classB: 'Satellite' },
  },
  {
    id: 'disjoint-maritime-satellite',
    type: 'disjoint',
    description: 'Maritime and Satellite are disjoint',
    params: { classA: 'Maritime', classB: 'Satellite' },
  },
  {
    id: 'satellite-altitude-min',
    type: 'value-restriction',
    description: 'Satellite altitude must be >= 80 km',
    params: { className: 'Satellite', property: 'altitude', min: 80_000 },
  },
  {
    id: 'aircraft-altitude-max',
    type: 'value-restriction',
    description: 'Aircraft altitude must be <= 50,000 ft (~15.24 km)',
    params: { className: 'Aircraft', property: 'altitude', max: 15_240 },
  },
  {
    id: 'maritime-speed-max',
    type: 'value-restriction',
    description: 'Maritime speed typically <= 60 knots',
    params: { className: 'Maritime', property: 'speed', max: 60 },
  },
  {
    id: 'subclass-fixedwing-aircraft',
    type: 'subclass',
    description: 'FixedWing is a subclass of Aircraft',
    params: { subclassId: 'FixedWing', superclassId: 'Aircraft' },
  },
  {
    id: 'subclass-rotarywing-aircraft',
    type: 'subclass',
    description: 'RotaryWing is a subclass of Aircraft',
    params: { subclassId: 'RotaryWing', superclassId: 'Aircraft' },
  },
  {
    id: 'subclass-leo-satellite',
    type: 'subclass',
    description: 'LEOSatellite is a subclass of Satellite',
    params: { subclassId: 'LEOSatellite', superclassId: 'Satellite' },
  },
  {
    id: 'subclass-geo-satellite',
    type: 'subclass',
    description: 'GEOSatellite is a subclass of Satellite',
    params: { subclassId: 'GEOSatellite', superclassId: 'Satellite' },
  },
  {
    id: 'subclass-intel-mission',
    type: 'subclass',
    description: 'IntelMission is a subclass of Mission',
    params: { subclassId: 'IntelMission', superclassId: 'Mission' },
  },
  {
    id: 'subclass-combat-mission',
    type: 'subclass',
    description: 'CombatMission is a subclass of Mission',
    params: { subclassId: 'CombatMission', superclassId: 'Mission' },
  },
  {
    id: 'cardinality-mission-assets',
    type: 'cardinality',
    description: 'A mission must have at least 1 asset assigned',
    params: { className: 'Mission', relation: 'has-asset', min: 1 },
  },
  {
    id: 'geofence-priority-critical',
    type: 'value-restriction',
    description: 'Critical-priority geofences must be active',
    params: { className: 'Geofence', property: 'priority', equals: 'critical' },
  },
]
