import type { Region } from '@/types'

export const regions: Region[] = [
  {
    id: 'indian-ocean',
    name: 'Indian Ocean',
    bounds: [30, -40, 120, 20],
    center: { latitude: -10, longitude: 75, altitude: 0 },
    threatLevel: 'medium',
    activeMissions: ['OP-Indian-Sentinel'],
    assetCount: 14,
    alertCount: 3,
  },
  {
    id: 'pacific',
    name: 'Pacific Ocean',
    bounds: [120, -40, -70, 40],
    center: { latitude: 0, longitude: -155, altitude: 0 },
    threatLevel: 'low',
    activeMissions: ['OP-Pacific-Watch'],
    assetCount: 22,
    alertCount: 1,
  },
  {
    id: 'mediterranean',
    name: 'Mediterranean',
    bounds: [-10, 30, 40, 48],
    center: { latitude: 36, longitude: 15, altitude: 0 },
    threatLevel: 'high',
    activeMissions: ['OP-Med-Shield', 'OP-EUNAVFOR'],
    assetCount: 18,
    alertCount: 7,
  },
  {
    id: 'north-atlantic',
    name: 'North Atlantic',
    bounds: [-80, 30, -10, 65],
    center: { latitude: 48, longitude: -40, altitude: 0 },
    threatLevel: 'medium',
    activeMissions: ['OP-Atlantic-Patrol'],
    assetCount: 11,
    alertCount: 2,
  },
  {
    id: 'south-china-sea',
    name: 'South China Sea',
    bounds: [100, 0, 125, 25],
    center: { latitude: 12, longitude: 115, altitude: 0 },
    threatLevel: 'critical',
    activeMissions: ['OP-SCS-Presence', 'OP-SPRATLY'],
    assetCount: 31,
    alertCount: 12,
  },
]
